export default {
    albon: "Albon",
    bottas: "Bottas",
    gasly: "Gasly",
    giovinazzi: "Giovinazzi",
    grosjean: "Grosjean",
    hamilton: "Hamilton",
    hulkenberg: "Hulkenberg",
    kubica: "Kubica",
    kvyat: "Kvyat",
    leclerc: "Leclerc",
    kevin_magnussen: "Magnussen",
    norris: "Norris",
    perez: "Perez",
    raikkonen: "Raikkonen",
    ricciardo: "Ricciardo",
    russell: "Russell",
    sainz: "Sainze",
    stroll: "Stroll",
    max_verstappen: "Verstappen",
    vettel: "Vettel"
}