const flags = {
    American: '🇺🇸',
    Argentine: '🇦🇷',
    Australian: '🇦🇺',
    Austrian: '🇦🇹',
    Belgian: '🇧🇪',
    Brazilian: '🇧🇷',
    British: '🇬🇧',
    Canadian: '🇨🇦',
    Colombian: '🇨🇴',
    Danish: '🇩🇰',
    Dutch: '🇳🇱',
    Finnish: '🇫🇮',
    French: '🇫🇷',
    German: '🇩🇪',
    Indian: '🇮🇳',
    Irish: '🇮🇪',
    Italian: '🇮🇹',
    Japanese: '🇯🇵',
    Mexican: '🇲🇽',
    Monegasque: '🇲🇨',
    'New Zealander': '🇳🇿',
    Polish: '🇵🇱',
    Portuguese: '🇵🇹',
    Russian: '🇷🇺',
    Spanish: '🇪🇸',
    Swedish: '🇸🇪',
    Swiss: '🇨🇭',
    Thai: '🇹🇭',
    Venezuelan: '🇻🇪'
}

export default flags