export const FETCH_CURRENT_RESULTS = 'FETCH_CURRENT_RESULTS'
export const FETCH_RESULT = 'FETCH_RESULT'
export const FETCH_QUALIFYING_RESULT = 'FETCH_QUALIFYING_RESULT'
export const FETCH_DRIVERS = 'FETCH_DRIVERS'